name: Test Devenv Setup

on:
  push:
    branches: [ main ]
    paths:
      - 'devenv.nix'
      - 'devenv.lock'
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-devenv:
    name: Test Devenv Setup
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Install Nix using the dedicated GitHub Action
      - name: Install Nix
        uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
      
      # Install devenv using cachix's GitHub Action
      - name: Install devenv
        uses: cachix/devenv-install-action@v1
      
      - name: Run tests with devenv
        run: |
          # Run tests with the Python version from devenv
          echo "=== Testing Python version ==="
          devenv shell -- python --version
          
          # Check if uv is available
          echo "=== Checking uv installation ==="
          devenv shell -- uv --version || echo "uv not installed"
          
          # Install package with uv
          echo "=== Installing package with uv ==="
          devenv shell -- uv pip install .[all] || devenv shell -- pip install .[all]
          
          # Run unittest tests
          echo "=== Running unittest tests ==="
          devenv shell -- python -m unittest discover tests/
          
          # Run pytest tests
          echo "=== Running pytest tests ==="
          devenv shell -- pytest tests/
          
          # List installed packages
          echo "=== Installed packages ==="
          devenv shell -- pip list