name: examples
on:
  push:
    paths:
      - "examples/**.py"
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Nix
        run: |
          sudo apt-get update
          sudo apt-get install -y curl xz-utils
          # Install Nix with multi-user support and flake support
          curl -L https://nixos.org/nix/install | sh -s -- --daemon --accept-flake-config
          # Add Nix to PATH
          echo "PATH=$HOME/.nix-profile/bin:$PATH" >> $GITHUB_ENV

          # Ensure correct permissions for /nix directory
          sudo chown -R runner:runner /nix

          # Check nix-daemon status
          systemctl status nix-daemon.service

          # Enable and start nix-daemon service if not running
          if ! systemctl is-active --quiet nix-daemon.service; then
            sudo systemctl enable nix-daemon.service
            sudo systemctl start nix-daemon.service
          fi

          # Source nix.sh
          . "$HOME/.nix-profile/etc/profile.d/nix.sh"

      - name: Configure Nix Channels
        run: |
          # Add the nixos-unstable channel
          nix-channel --add https://nixos.org/channels/nixos-unstable
          # Update channels
          nix-channel --update

      - name: Install devenv
        run: |
          # Install the devenv package
          nix profile install nixpkgs#devenv

      - name: Setup devenv Environment
        run: |
          # Initialize devenv using the devenv.nix file
          devenv init -f devenv.nix

          # Run devenv shell to capture environment variables
          devenv shell --no-status --impure bash -c "
            echo \"PYTHONPATH=\${PYTHONPATH}\" >> .env_cache
            echo \"PROJECT_DIR=\${PROJECT_DIR}\" >> .env_cache
            env >> .env_cache
          "

          # Source the captured environment variables
          . .env_cache

      - name: Install Project Dependencies
        run: |
          # Use devenv shell to install dependencies
          devenv shell --no-status --impure bash -c "
            python --version
            uv pip install --no-cache-dir Cython
            uv pip install -e .[all]
          "

      - name: Set executable permissions
        run: chmod +x tests/test_examples.sh

      - name: Run Tests
        run: |
          # Use devenv shell to run tests
          devenv shell --no-status --impure bash -c "./tests/test_examples.sh examples/"