name: examples
on:
  push:
    paths:
      - "examples/**/*.py"
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Nix (Recommended Method)
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            build-users-group =

      - name: Verify Nix Installation
        run: |
          nix --version
          nix-channel --list

      - name: Restore Nix environment cache
        uses: actions/cache@v4
        id: nix-cache
        with:
          path: |
            /nix
            ~/.nix-profile
            ~/.devenv
            .direnv
            .env_cache
          key: nix-${{ runner.os }}-${{ hashFiles('devenv.nix', 'devenv.lock', 'devenv.yaml', 'flake.nix', 'flake.lock') }}
          restore-keys: |
            nix-${{ runner.os }}-

      - name: Install devenv
        run: |
          nix profile install nixpkgs#devenv || nix-env -iA nixpkgs.devenv
          devenv --version

      - name: Setup devenv Environment
        run: |
          if [ -f .env_cache ] && [ -s .env_cache ] && [ "${{ steps.nix-cache.outputs.cache-hit }}" == "true" ]; then
            echo "Using cached environment"
            source .env_cache
          else
            echo "Setting up environment from scratch"
            devenv init || { echo "Failed to initialize devenv"; exit 1; }
            direnv allow . && eval "$(direnv export bash)"
            python --version || { echo "Python setup failed"; exit 1; }
            echo "PYTHONPATH=${PYTHONPATH}" >> .env_cache
            echo "PROJECT_DIR=${PROJECT_DIR}" >> .env_cache
            env >> .env_cache
          fi

      - name: Install Dependencies
        run: |
          uv pip install --no-cache-dir Cython
          uv pip install -e .[all]

      - name: Run Tests
        run: |
          ./tests/test_examples.sh examples/
