name: examples
on:
  push:
    paths:
      - "examples/**.py"
  workflow_dispatch:  # Allows manual trigger

jobs:
  linux:
    runs-on: ubuntu-latest
    container:
      image: notoo1/ubuntu-nix:24.04-8  # Public container

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set executable permissions
        run: chmod +x tests/test_examples.sh

      - name: Restore Nix environment
        uses: actions/cache@v4
        id: nix-cache
        with:
          path: |
            ~/.nix-profile
            /nix/store
            .direnv
            .env_cache
          key: ${{ runner.os }}-devenv-python312-${{ hashFiles('devenv.nix', 'devenv.lock') }}
          restore-keys: |
            ${{ runner.os }}-devenv-python312-

      - name: Setup devenv Environment
        run: |
          # If the environment is cached, use it
          if [ -f .env_cache ] && [ "${{ steps.nix-cache.outputs.cache-hit }}" == "true" ]; then
            echo "Using cached environment"
            source .env_cache
          else
            echo "Setting up environment from scratch using devenv"
            
            # Initialize the devenv environment from devenv.nix and devenv.lock
            devenv init

            # Ensure the environment variables are cached for future use
            devenv shell --no-status --impure bash -c "
              echo \"PYTHONPATH=\${PYTHONPATH}\" >> .env_cache
              echo \"PROJECT_DIR=\${PROJECT_DIR}\" >> .env_cache
              env >> .env_cache
            "
          fi

          # Debugging the environment
          echo "Environment Variables:"
          echo "PYTHONPATH=$PYTHONPATH"
          echo "PROJECT_DIR=$PROJECT_DIR"

          # Load the cached environment
          source .env_cache

      - name: Install dependencies
        run: |
          devenv shell --no-status --impure bash -c "
            # Print Python version
            python --version

            # Install Cython first (using uv as specified)
            uv pip install --no-cache-dir Cython

            # Install the package in development mode
            uv pip install -e .[all]
          "

      - name: Run Tests
        run: |
          devenv shell --no-status --impure bash -c "./tests/test_examples.sh examples/"
