name: examples

on:
  push:
    paths:
      - "examples/**/*.py"
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            build-users-group =

      - name: Verify Nix Installation
        run: |
          nix --version
          nix-channel --list

      - name: Restore Nix environment cache
        uses: actions/cache@v4
        id: nix-cache
        with:
          path: |
            /nix
            ~/.nix-profile
            ~/.devenv
            .direnv
            .env_cache
          key: nix-${{ runner.os }}-${{ hashFiles('devenv.nix', 'devenv.lock', 'flake.nix', 'flake.lock') }}
          restore-keys: |
            nix-${{ runner.os }}-

      - name: Ensure devenv Is Installed
        run: |
          nix profile install nixpkgs#devenv || nix-env -iA nixpkgs.devenv
          devenv --version

      - name: Setup environment from flake.nix
        run: |
          if [ ! -f flake.nix ]; then
            echo "Error: flake.nix not found. Make sure the file is committed."
            exit 1
          fi
          
          echo "Setting up environment from flake.nix"
          # Use devenv shell directly to ensure proper environment setup
          devenv shell --impure --command "echo 'Environment activated'"

      - name: Install Dependencies
        run: |
          devenv shell --impure --command "uv pip install --no-cache-dir Cython"
          devenv shell --impure --command "uv pip install -e .[all]"

      - name: Run Tests
        run: |
          devenv shell --impure --command "./tests/test_examples.sh examples/"