name: examples
on:
  push:
    paths:
      - "examples/**.py"
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Nix
        run: |
          sudo apt-get update
          sudo apt-get install -y curl xz-utils
          curl -L https://nixos.org/nix/install | sh -s -- --daemon
          echo "PATH=$HOME/.nix-profile/bin:$PATH" >> $GITHUB_ENV
          sudo systemctl restart nix-daemon
          . "$HOME/.nix-profile/etc/profile.d/nix.sh"

      - name: Update Nixpkgs
        run: nix-channel --update

      - name: check nix health
        run: nix-store --verify --check-contents --repair

      - name: Install devenv
        run: nix profile install nixpkgs#devenv

      - name: Setup devenv Environment
        run: |
          devenv init
          devenv shell --no-status --impure bash -c "
            echo \"PYTHONPATH=\${PYTHONPATH}\" >> .env_cache
            echo \"PROJECT_DIR=\${PROJECT_DIR}\" >> .env_cache
            env >> .env_cache
          "
          . .env_cache

      - name: Install dependencies from devenv.nix and devenv.lock
        run: |
          devenv shell --no-status --impure bash -c "
            python --version
            uv pip install --no-cache-dir Cython
            uv pip install -e .[all]
          "

      - name: Set executable permissions
        run: chmod +x tests/test_examples.sh

      - name: Run Tests
        run: |
          devenv shell --no-status --impure bash -c "./tests/test_examples.sh examples/"