name: examples
on:
  push:
    paths:
      - "examples/**.py"
  workflow_dispatch:  # Adding manual trigger option

jobs:
  linux:
    runs-on: ubuntu-latest
    container:
      image: notoo1/ubuntu-nix:24.04-8
      credentials:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      # Add this step after checkout
      - name: Set executable permissions
        run: |
          chmod +x tests/test_examples.sh
          
      - name: Restore Nix environment
        uses: actions/cache@v4
        id: nix-cache
        with:
          path: |
            ~/.nix-profile
            ~/.devenv
            .direnv
            .env_cache
          key: ${{ runner.os }}-nix-python312-${{ hashFiles('devenv.nix', 'devenv.lock', 'devenv.yaml', 'flake.nix', 'flake.lock') }}
          restore-keys: |
            ${{ runner.os }}-nix-python312-
            
      - name: Setup devenv Environment
        run: |
          if [ -f .env_cache ] && [ "${{ steps.nix-cache.outputs.cache-hit }}" == "true" ]; then
            echo "Using cached environment"
            source .env_cache
          else
            echo "Setting up environment from scratch"
            if ! command -v devenv &> /dev/null; then
              echo "Installing devenv..."
              nix profile install --accept-flake-config "nixpkgs#devenv"
            fi
            
            # Initialize devenv with Python 3.12 from the default configuration
            echo "Initializing devenv with Python 3.12 configuration..."
            devenv init
          fi
          
          # Ensure we use the correct Python from devenv.nix
          direnv allow . && eval "$(direnv export bash)"
          
          # Verify Python version
          python --version
          
          # Export important environment variables for future jobs
          echo "PYTHONPATH=${PYTHONPATH}" >> .env_cache
          echo "PROJECT_DIR=${PROJECT_DIR}" >> .env_cache
          env >> .env_cache
          
      - name: Install dependencies
        run: |
          # Using UV from devenv.nix instead of pip
          echo "Installing dependencies with UV from devenv..."
          
          # Install Cython first
          uv pip install --no-cache-dir Cython
          
          # Install the package in development mode
          uv pip install -e .[all]
          
      - name: Run Tests
        run: |
          ./tests/test_examples.sh examples/