name: examples
on:
  push:
    paths:
      - "examples/**/*.py"
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04  # Use official Ubuntu image

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install curl
        run: |
          echo "Installing curl..."
          apt-get update && apt-get install -y curl

      - name: Install Nix (Clean Installation)
        run: |
          echo "Installing Nix..."
          curl -L https://nixos.org/nix/install | sh
          
          # Ensure Nix is available after installation
          . $HOME/.nix-profile/etc/profile.d/nix.sh
          echo "Nix Version:"
          nix --version

      - name: Restore Nix environment cache
        uses: actions/cache@v4
        id: nix-cache
        with:
          path: |
            /nix
            ~/.nix-profile
            ~/.devenv
            .direnv
            .env_cache
          key: nix-${{ runner.os }}-${{ hashFiles('devenv.nix', 'devenv.lock', 'devenv.yaml', 'flake.nix', 'flake.lock') }}
          restore-keys: |
            nix-${{ runner.os }}-

      - name: Install devenv (Safe Method)
        run: |
          if ! command -v devenv &> /dev/null; then
            echo "Installing devenv using nix-env..."
            nix-env -iA nixpkgs.devenv || { echo "devenv installation failed!"; exit 1; }
          else
            echo "devenv is already installed"
          fi

      - name: Setup devenv Environment
        run: |
          if [ -f .env_cache ] && [ -s .env_cache ] && [ "${{ steps.nix-cache.outputs.cache-hit }}" == "true" ]; then
            echo "Using cached environment"
            source .env_cache
          else
            echo "Setting up environment from scratch"
            devenv init || { echo "Failed to initialize devenv"; exit 1; }
            direnv allow . && eval "$(direnv export bash)"
            python --version || { echo "Python setup failed"; exit 1; }
            echo "PYTHONPATH=${PYTHONPATH}" >> .env_cache
            echo "PROJECT_DIR=${PROJECT_DIR}" >> .env_cache
            env >> .env_cache
          fi

      - name: Install Dependencies
        run: |
          uv pip install --no-cache-dir Cython
          uv pip install -e .[all]

      - name: Run Tests
        run: |
          ./tests/test_examples.sh examples/
