name: examples
on:
  push:
    paths:
      - "examples/**/*.py"  # Fixes glob pattern to include subdirectories
  workflow_dispatch:  # Allows manual triggering

jobs:
  linux:
    runs-on: ubuntu-latest
    container:
      image: notoo1/ubuntu-nix:24.04-8
    defaults:
      run:
        shell: bash  # Ensure we use bash instead of sh

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Verify test script exists & set permissions
        run: |
          if [ -f tests/test_examples.sh ]; then
            chmod +x tests/test_examples.sh
          else
            echo "ERROR: tests/test_examples.sh not found!"
            exit 1
          fi

      - name: Restore Nix environment cache
        uses: actions/cache@v4
        id: nix-cache
        with:
          path: |
            /nix
            ~/.nix-profile
            ~/.devenv
            .direnv
            .env_cache
          key: nix-${{ runner.os }}-${{ hashFiles('devenv.nix', 'devenv.lock', 'devenv.yaml', 'flake.nix', 'flake.lock') }}
          restore-keys: |
            nix-${{ runner.os }}-

      - name: Ensure Nix is installed and initialized
        run: |
          if ! command -v nix &> /dev/null; then
            echo "ERROR: Nix should be preinstalled in the container but is missing!"
            exit 1
          fi
          echo "Nix is installed at: $(command -v nix)"

          # Ensure Nix environment is loaded
          . /etc/profile || { echo "Failed to load Nix environment"; exit 1; }
          echo "Nix environment initialized."

      - name: Setup devenv Environment
        run: |
          if [ -f .env_cache ] && [ -s .env_cache ] && [ "${{ steps.nix-cache.outputs.cache-hit }}" == "true" ]; then
            echo "Using cached environment"
            source .env_cache
          else
            echo "Setting up environment from scratch"

            if ! command -v devenv &> /dev/null; then
              echo "Installing devenv..."
              nix profile install --accept-flake-config "nixpkgs#devenv"
            fi

            devenv init || { echo "Failed to initialize devenv"; exit 1; }

            direnv allow . && eval "$(direnv export bash)"

            python --version || { echo "Python setup failed"; exit 1; }

            echo "PYTHONPATH=${PYTHONPATH}" >> .env_cache
            echo "PROJECT_DIR=${PROJECT_DIR}" >> .env_cache
            env >> .env_cache
          fi

      - name: Verify UV installation
        run: |
          if ! command -v uv &> /dev/null; then
            echo "ERROR: UV is not installed!"
            exit 1
          fi

      - name: Install dependencies
        run: |
          echo "Installing dependencies with UV..."
          uv pip install --no-cache-dir Cython
          uv pip install -e .[all]

      - name: Debug Environment Variables
        run: env | sort  # Helps diagnose missing env variables

      - name: Run Tests
        run: |
          ./tests/test_examples.sh examples/
